import Head from 'next/head'

export default function Index() {
    return (
        <div>
            <Head>
                <title>Menu 1</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>Menu 1</h1>
        </div>
    )
}